SELECT
--FROM raw_orders
O.ORDERID,
O.ORDERDATE,
O.SHIPDATE,
O.SHIPMODE,
O.ORDERSELLINGPRICE-O.ORDERCOSTPRICE AS ORDERPROFIT,
O.ORDERCOSTPRICE,
O.ORDERSELLINGPRICE,
--FROM raw_customers
C.CUSTOMERNAME,
C.SEGMENT,
C.COUNTRY,
--FROM raw_product
P.CATEGORY,
P.PRODUCTNAME,
P.SUBCATEGORY
FROM {{ ref('raw_orders') }} AS O
LEFT JOIN {{ ref('raw_customers') }} AS C
ON O.CUSTOMERID = C.CUSTOMERID
LEFT JOIN {{ ref('raw_products') }} AS P
ON O.PRODUCTID = P.PRODUCTID